name: deploy-to-staging
on:
  pull_request:
    types:
      - closed

jobs:
  pre-commit_and_test:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: pre-commit_and_test
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  ready-for-qa:
    needs: deploy
    uses: ./.github/workflows/ready-for-qa.yml