name: deploy-to-staging
on:
  push:
    branches:
      # When someone push to `master` branch
      - master

jobs:
  pre-commit_and_test:
    uses: ./.github/workflows/ci.yml
  deploy:
    concurrency: 
      group: ${{ github.head_ref || github.run_id }}
    needs: pre-commit_and_test
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"